name: eco_ideas
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  crypto: ^3.0.3
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.2
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0 
  
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.3
 
  formz: ^0.6.1
  freezed_annotation: ^2.4.1
  go_router: ^12.0.0
  
 
  
  http: ^1.2.1
  image_picker: ^1.0.5
  intl: ^0.18.0
  json_annotation: ^4.8.1
  
  riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0
  rxdart: ^0.27.7
  supabase_flutter: ^1.8.1

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
  go_router_builder: ^2.3.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/
