name: eco_ideas
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  email_validator: ^3.0.0
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.2.1

  flutter_exif_rotation: ^0.5.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  go_router_builder: ^2.7.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  spacing_generator_annotation: ^0.3.0
  supabase_flutter: ^2.8.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.3
  spacing_generator: ^0.4.0+5
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/
